config/routes.rb
EducationalInstituation::Application.routes.draw do

  resources :courses do
    resources :syllabuses do
      resources :chapters
    end
  end

  devise_for :users

  root :to => "home#index"
  

end

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Chakra Institute"
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"


  %body
    .navbar.navbar-default.navbar-static-top
      .container
        %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand(href="#") Chakra Institute
        - if user_signed_in?
          .navbar-collapse.collapse.navbar-responsive-collapse
            %ul.nav.navbar-nav
              %li= link_to "About Us", "#"
              %li= link_to "Contact Us", "#"
              %li= link_to "Carrers", "#"
              %li= link_to "Blog", "#"
              
           
    .container
      .row{:style => "min-height:500px;"}
        .col-lg-9
          #breadcrumb
          = breadcrumbs separator: " &rsaquo; "   
          %br
          = bootstrap_flash
          = yield
        .col-lg-3
          - if user_signed_in?
            .well.sidebar-nav
              %h3 Administration
              %ul.nav.nav-list
                %li.nav-header Settings
                %li= link_to("Change Password", edit_user_registration_path)
                %li= link_to('Logout', destroy_user_session_path, :method => :delete)
                %li.nav-header Actions
                %li= link_to("Courses" , courses_url)
                = yield :sidebar

          
      %footer
        %p &copy; Chakra Institute #{Date.today.year}